//! `projects` / `persons_projects`.
//!
//! `ProjectMetadataV5` and `ProjectSettingsV5` both implement `sqlx::FromRow` (the former
//! directly on the local type in `storage::project_storage::current`, the latter on the
//! `vb-exchange` type itself, behind its `sqlx` feature — see their `FromRow` impls for the
//! per-field mapping notes). `ProjectMetadataV5`'s `authors`/`editors` still need a separate
//! fetch from the `persons_projects` join afterward, since that's not a plain column.
//!
//! Known schema gaps (inherited from the existing migration/schema, not introduced here):
//! `ProjectSettingsV5.metadata_page_additional_html` has no column, always round-trips as
//! `None`. `title` is the single unified column for both the old `ProjectData.name` and
//! `ProjectMetadata.title` (which could previously diverge) — every write keeps them equal.

use super::DbError;
use crate::storage::project_storage::current::{
    PersonUuidOrString, ProjectMetadataV5, license_to_string,
};
use sqlx::postgres::PgExecutor;
use sqlx::types::Json;
use sqlx::{PgPool, Postgres, Transaction};
use std::collections::HashMap;
use uuid::Uuid;
use vb_exchange::projects::{Identifier, Keyword, ProjectSettingsV5};

/// Checks whether a project with the given id exists.
pub async fn exists<'e>(exec: impl PgExecutor<'e>, id: Uuid) -> Result<bool, DbError> {
    let exists = sqlx::query_scalar!("SELECT EXISTS(SELECT 1 FROM projects WHERE id = $1)", id)
        .fetch_one(exec)
        .await?;
    Ok(exists.unwrap_or(false))
}

/// Inserts a new project row. `id` is generated by the caller (rather than relying on the
/// column default + `RETURNING`) so callers can prepare on-disk state (e.g. an uploads
/// directory) under the same id before/without a round trip.
#[allow(clippy::too_many_arguments)]
pub async fn insert(
    pool: &PgPool,
    id: Uuid,
    title: &str,
    description: Option<&str>,
    template_id: Option<Uuid>,
    folder: Option<Uuid>,
    owner_team_id: Uuid,
) -> Result<(), DbError> {
    sqlx::query!(
        "INSERT INTO projects (id, title, description, template_id, folder, owner_team_id)
         VALUES ($1, $2, $3, $4, $5, $6)",
        id,
        title,
        description,
        template_id,
        folder,
        owner_team_id
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Fetches a project's title.
pub async fn get_title<'e>(exec: impl PgExecutor<'e>, id: Uuid) -> Result<String, DbError> {
    sqlx::query_scalar!("SELECT title FROM projects WHERE id = $1", id)
        .fetch_optional(exec)
        .await?
        .ok_or(DbError::NotFound("project"))
}

/// Updates a project's title. Fails with [`DbError::NotFound`] if no project with that id exists.
pub async fn update_title<'e>(
    exec: impl PgExecutor<'e>,
    id: Uuid,
    title: &str,
) -> Result<(), DbError> {
    let result = sqlx::query!("UPDATE projects SET title = $2 WHERE id = $1", id, title)
        .execute(exec)
        .await?;
    if result.rows_affected() == 0 {
        return Err(DbError::NotFound("project"));
    }
    Ok(())
}

/// Fetches a project's assigned template id, if any.
pub async fn get_template_id<'e>(
    exec: impl PgExecutor<'e>,
    id: Uuid,
) -> Result<Option<Uuid>, DbError> {
    sqlx::query_scalar!("SELECT template_id FROM projects WHERE id = $1", id)
        .fetch_optional(exec)
        .await?
        .ok_or(DbError::NotFound("project"))
}

/// Updates a project's assigned template.
pub async fn update_template<'e>(
    exec: impl PgExecutor<'e>,
    id: Uuid,
    template_id: Option<Uuid>,
) -> Result<(), DbError> {
    let result = sqlx::query!(
        "UPDATE projects SET template_id = $2 WHERE id = $1",
        id,
        template_id
    )
    .execute(exec)
    .await?;
    if result.rows_affected() == 0 {
        return Err(DbError::NotFound("project"));
    }
    Ok(())
}

/// Deletes a project by id. Fails with [`DbError::NotFound`] if no row with that id exists.
pub async fn delete<'e>(exec: impl PgExecutor<'e>, id: Uuid) -> Result<(), DbError> {
    let result = sqlx::query!("DELETE FROM projects WHERE id = $1", id)
        .execute(exec)
        .await?;
    if result.rows_affected() == 0 {
        return Err(DbError::NotFound("project"));
    }
    Ok(())
}

/// Fetches a project's description.
pub async fn get_description<'e>(
    exec: impl PgExecutor<'e>,
    id: Uuid,
) -> Result<Option<String>, DbError> {
    sqlx::query_scalar!("SELECT description FROM projects WHERE id = $1", id)
        .fetch_optional(exec)
        .await?
        .ok_or(DbError::NotFound("project"))
}

/// Updates a project's description.
pub async fn update_description<'e>(
    exec: impl PgExecutor<'e>,
    id: Uuid,
    description: Option<&str>,
) -> Result<(), DbError> {
    let result = sqlx::query!(
        "UPDATE projects SET description = $2 WHERE id = $1",
        id,
        description
    )
    .execute(exec)
    .await?;
    if result.rows_affected() == 0 {
        return Err(DbError::NotFound("project"));
    }
    Ok(())
}

/// Loads a project's author/editor links from `persons_projects`, ordered by `position`,
/// split into separate author/editor lists.
async fn fetch_persons<'e>(
    exec: impl PgExecutor<'e>,
    project_id: Uuid,
) -> Result<(Vec<PersonUuidOrString>, Vec<PersonUuidOrString>), DbError> {
    let rows = sqlx::query!(
        "SELECT role, person_id, name FROM persons_projects WHERE project_id = $1 ORDER BY position",
        project_id
    )
    .fetch_all(exec)
    .await?;

    let mut authors = Vec::new();
    let mut editors = Vec::new();
    for row in rows {
        let person = match row.person_id {
            Some(id) => PersonUuidOrString::PersonUuid(id),
            None => PersonUuidOrString::NameString(row.name.unwrap_or_default()),
        };
        match row.role.as_str() {
            "author" => authors.push(person),
            "editor" => editors.push(person),
            _ => {}
        }
    }
    Ok((authors, editors))
}

/// Replaces a project's author/editor links (delete-then-reinsert), preserving list order
/// via the `position` column.
async fn replace_persons(
    tx: &mut Transaction<'_, Postgres>,
    project_id: Uuid,
    authors: &[PersonUuidOrString],
    editors: &[PersonUuidOrString],
) -> Result<(), DbError> {
    sqlx::query!(
        "DELETE FROM persons_projects WHERE project_id = $1",
        project_id
    )
    .execute(&mut **tx)
    .await?;
    for (people, role) in [(authors, "author"), (editors, "editor")] {
        for (index, person) in people.iter().enumerate() {
            let (person_id, name) = match person {
                PersonUuidOrString::PersonUuid(id) => (Some(*id), None),
                PersonUuidOrString::NameString(name) => (None, Some(name.clone())),
            };
            sqlx::query!(
                "INSERT INTO persons_projects (person_id, name, project_id, role, position) VALUES ($1, $2, $3, $4, $5)",
                person_id,
                name,
                project_id,
                role,
                index as f64
            )
            .execute(&mut **tx)
            .await?;
        }
    }
    Ok(())
}

/// Fetches a project's metadata, including its authors/editors.
pub async fn get_metadata(pool: &PgPool, id: Uuid) -> Result<ProjectMetadataV5, DbError> {
    let mut tx = pool.begin().await?;
    let metadata = get_metadata_in_tx(&mut tx, id).await?;
    tx.commit().await?;
    Ok(metadata)
}

/// Transaction-scoped variant of [`get_metadata`], for callers (e.g. `patch_project`) that
/// need to read-then-write metadata as part of a single larger atomic transaction.
pub(crate) async fn get_metadata_in_tx(
    tx: &mut Transaction<'_, Postgres>,
    id: Uuid,
) -> Result<ProjectMetadataV5, DbError> {
    let mut metadata: ProjectMetadataV5 = sqlx::query_as(
        r#"SELECT title, subtitle, web_url, publish_date, languages, number_of_pages,
                  short_abstract, long_abstract, ddc, license, series, volume, edition, publisher,
                  keywords, custom_fields, identifiers
           FROM projects WHERE id = $1"#,
    )
    .bind(id)
    .fetch_optional(&mut **tx)
    .await?
    .ok_or(DbError::NotFound("project"))?;

    let (authors, editors) = fetch_persons(&mut **tx, id).await?;
    metadata.authors = Some(authors);
    metadata.editors = Some(editors);
    Ok(metadata)
}

/// Fetches a project's settings.
pub async fn get_settings(pool: &PgPool, id: Uuid) -> Result<ProjectSettingsV5, DbError> {
    let mut tx = pool.begin().await?;
    let settings = get_settings_in_tx(&mut tx, id).await?;
    tx.commit().await?;
    Ok(settings)
}

/// Transaction-scoped variant of [`get_settings`], see [`get_metadata_in_tx`]. `vb_exchange`
/// implements `sqlx::FromRow` for `ProjectSettingsV5` directly (behind its `sqlx` feature), so
/// this reads straight into the domain struct via runtime `query_as` rather than macro-checked
/// `query_as!` + manual field assembly.
pub(crate) async fn get_settings_in_tx(
    tx: &mut Transaction<'_, Postgres>,
    id: Uuid,
) -> Result<ProjectSettingsV5, DbError> {
    let settings: ProjectSettingsV5 = sqlx::query_as(
        "SELECT toc_enabled, csl_style, csl_language_code, cover_image_path, backcover_image_path, add_soft_hyphens
         FROM projects WHERE id = $1",
    )
    .bind(id)
    .fetch_optional(&mut **tx)
    .await?
    .ok_or(DbError::NotFound("project"))?;
    Ok(settings)
}

/// Overwrites every metadata column (title is handled separately via [`update_title`], since
/// it's shared with the old `ProjectData.name` field) plus the author/editor link rows.
pub async fn update_metadata(
    pool: &PgPool,
    id: Uuid,
    metadata: &ProjectMetadataV5,
) -> Result<(), DbError> {
    let mut tx = pool.begin().await?;
    update_metadata_in_tx(&mut tx, id, metadata).await?;
    tx.commit().await?;
    Ok(())
}

/// Transaction-scoped variant of [`update_metadata`], see [`get_metadata_in_tx`].
pub(crate) async fn update_metadata_in_tx(
    tx: &mut Transaction<'_, Postgres>,
    id: Uuid,
    metadata: &ProjectMetadataV5,
) -> Result<(), DbError> {
    let languages: Option<Vec<String>> = metadata
        .languages
        .as_ref()
        .map(|langs| langs.iter().map(|l| l.as_tag().to_string()).collect());
    let license = metadata.license.as_ref().map(license_to_string);

    let result = sqlx::query!(
        r#"UPDATE projects SET
            subtitle = $2, web_url = $3, publish_date = $4, languages = $5, number_of_pages = $6,
            short_abstract = $7, long_abstract = $8, ddc = $9, license = $10, series = $11,
            volume = $12, edition = $13, publisher = $14,
            keywords = $15, custom_fields = $16, identifiers = $17
         WHERE id = $1"#,
        id,
        metadata.subtitle,
        metadata.web_url,
        metadata.published,
        languages.as_deref(),
        metadata.number_of_pages.map(|n| n as i32),
        metadata.short_abstract,
        metadata.long_abstract,
        metadata.ddc,
        license,
        metadata.series,
        metadata.volume,
        metadata.edition,
        metadata.publisher,
        metadata.keywords.as_ref().map(Json) as Option<Json<&Vec<Keyword>>>,
        Json(&metadata.custom_fields) as Json<&HashMap<String, String>>,
        metadata.identifiers.as_ref().map(Json) as Option<Json<&Vec<Identifier>>>,
    )
    .execute(&mut **tx)
    .await?;
    if result.rows_affected() == 0 {
        return Err(DbError::NotFound("project"));
    }

    replace_persons(
        tx,
        id,
        metadata.authors.as_deref().unwrap_or(&[]),
        metadata.editors.as_deref().unwrap_or(&[]),
    )
    .await?;

    Ok(())
}

/// Overwrites every settings column for a project.
pub async fn update_settings<'e>(
    exec: impl PgExecutor<'e>,
    id: Uuid,
    settings: &ProjectSettingsV5,
) -> Result<(), DbError> {
    let result = sqlx::query!(
        r#"UPDATE projects SET
            toc_enabled = $2, csl_style = $3, csl_language_code = $4,
            cover_image_path = $5, backcover_image_path = $6, add_soft_hyphens = $7
         WHERE id = $1"#,
        id,
        settings.toc_enabled,
        settings.csl_style,
        settings.csl_language_code,
        settings.cover_image_path,
        settings.backcover_image_path,
        settings.add_soft_hyphens,
    )
    .execute(exec)
    .await?;
    if result.rows_affected() == 0 {
        return Err(DbError::NotFound("project"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::repositories::users;
    use vb_exchange::projects::License;

    #[sqlx::test]
    async fn insert_and_get_round_trip(pool: PgPool) -> sqlx::Result<()> {
        let team_id = users::ensure_default_team(&pool).await.unwrap();
        let id = Uuid::new_v4();
        insert(&pool, id, "My Project", None, None, None, team_id)
            .await
            .unwrap();

        assert!(exists(&pool, id).await.unwrap());
        assert_eq!(get_title(&pool, id).await.unwrap(), "My Project");
        Ok(())
    }

    #[sqlx::test]
    async fn owner_check_constraint_requires_exactly_one(pool: PgPool) -> sqlx::Result<()> {
        let team_id = users::ensure_default_team(&pool).await.unwrap();
        let user = users::insert(&pool, "owner@example.com", "Owner", "hash", team_id)
            .await
            .unwrap();

        let neither = sqlx::query!("INSERT INTO projects (title) VALUES ('No owner')")
            .execute(&pool)
            .await;
        assert!(neither.is_err());

        let both = sqlx::query!(
            "INSERT INTO projects (title, owner_team_id, owner_user_id) VALUES ('Both owners', $1, $2)",
            team_id,
            user.id
        )
        .execute(&pool)
        .await;
        assert!(both.is_err());
        Ok(())
    }

    #[sqlx::test]
    async fn update_template_rejects_unknown_project(pool: PgPool) -> sqlx::Result<()> {
        let result = update_template(&pool, Uuid::new_v4(), None).await;
        assert!(matches!(result, Err(DbError::NotFound("project"))));
        Ok(())
    }

    #[sqlx::test]
    async fn metadata_and_settings_round_trip(pool: PgPool) -> sqlx::Result<()> {
        let team_id = users::ensure_default_team(&pool).await.unwrap();
        let project_id = Uuid::new_v4();
        insert(
            &pool,
            project_id,
            "Original Title",
            None,
            None,
            None,
            team_id,
        )
        .await
        .unwrap();
        let person = crate::db::repositories::persons::insert;
        let person_id = Uuid::new_v4();
        let person_value = vb_exchange::projects::PersonV2 {
            id: Some(person_id),
            first_names: Some("A".to_string()),
            last_names: "Author".to_string(),
            orcid: None,
            gnd: None,
            ror: None,
            bios: None,
        };
        person(&pool, &person_value).await.unwrap();

        let mut metadata = get_metadata(&pool, project_id).await.unwrap();
        metadata.subtitle = Some("A subtitle".to_string());
        metadata.authors = Some(vec![PersonUuidOrString::PersonUuid(person_id)]);
        metadata.editors = Some(vec![PersonUuidOrString::NameString(
            "Guest Editor".to_string(),
        )]);
        metadata.license = Some(License::CC_BY_4);
        metadata.keywords = Some(vec![Keyword {
            title: "topic".to_string(),
            gnd: None,
        }]);
        metadata
            .custom_fields
            .insert("k".to_string(), "v".to_string());

        update_metadata(&pool, project_id, &metadata).await.unwrap();

        let fetched = get_metadata(&pool, project_id).await.unwrap();
        assert_eq!(fetched.subtitle, Some("A subtitle".to_string()));
        assert_eq!(
            fetched.authors,
            Some(vec![PersonUuidOrString::PersonUuid(person_id)])
        );
        assert_eq!(
            fetched.editors,
            Some(vec![PersonUuidOrString::NameString(
                "Guest Editor".to_string()
            )])
        );
        assert!(matches!(fetched.license, Some(License::CC_BY_4)));
        assert_eq!(fetched.keywords.unwrap()[0].title, "topic");
        assert_eq!(fetched.custom_fields.get("k"), Some(&"v".to_string()));

        let mut settings = get_settings(&pool, project_id).await.unwrap();
        settings.toc_enabled = true;
        settings.csl_style = Some("apa".to_string());
        update_settings(&pool, project_id, &settings).await.unwrap();
        let fetched_settings = get_settings(&pool, project_id).await.unwrap();
        assert!(fetched_settings.toc_enabled);
        assert_eq!(fetched_settings.csl_style, Some("apa".to_string()));
        Ok(())
    }
}
