use crate::db::repositories::persons;
use crate::session::session_guard::Session;
use crate::utils::api_helpers::{APIResponse, APIResult, ApiErrorType};
use rocket::State;
use rocket::serde::json::Json;
use sqlx::PgPool;
use vb_exchange::projects::Person;

/// POST /api/persons/
/// Create a new person
#[post("/api/persons", data = "<person>")]
pub async fn create_person(
    _session: Session,
    pool: &State<PgPool>,
    person: Json<Person>,
) -> APIResult<Person> {
    let mut person = person.into_inner();

    // Check if api request contains a person id, if so return an error as the id is generated by the server
    match person.id {
        Some(_) => {
            eprintln!("Person already has an id");
            return Err(ApiErrorType::BadRequest(
                "Person is not supposed to have an id".to_string(),
            )
            .into());
        }
        None => {
            person.id = Some(uuid::Uuid::new_v4());
        }
    }

    if let Some(ref mut gnd) = person.gnd {
        if gnd.id.is_none() {
            gnd.id = Some(uuid::Uuid::new_v4());
        } else {
            eprintln!("Persons gnd already has a id");
            return Err(
                ApiErrorType::BadRequest("GND is not supposed to have an id".to_string()).into(),
            );
        }
    };

    if let Some(ref mut orcid) = person.orcid {
        if orcid.id.is_none() {
            orcid.id = Some(uuid::Uuid::new_v4());
        } else {
            eprintln!("Persons orcid already has a id");
            return Err(ApiErrorType::BadRequest(
                "ORCID is not supposed to have an id".to_string(),
            )
            .into());
        }
    };

    if let Some(ref mut ror) = person.ror {
        if ror.id.is_none() {
            ror.id = Some(uuid::Uuid::new_v4());
        } else {
            eprintln!("Persons ror already has a id");
            return Err(
                ApiErrorType::BadRequest("ROR is not supposed to have an id".to_string()).into(),
            );
        }
    };

    persons::insert(pool.inner(), &person).await?;

    Ok(APIResponse::from(person))
}

/// PUT /api/persons/<id>
/// Update specified person
#[put("/api/persons/<id>", data = "<person>")]
pub async fn update_person(
    _session: Session,
    pool: &State<PgPool>,
    person: Json<Person>,
    id: &str,
) -> APIResult<Person> {
    let person = person.into_inner();

    // Check if id in url matches id in body
    match person.id {
        Some(ref person_id) => {
            let id = uuid::Uuid::parse_str(id)?;

            if *person_id != id {
                eprintln!("Person id in url doesn't match person id in body");
                return Err(ApiErrorType::BadRequest(
                    "Person id in url doesn't match person id in body. ID change is not allowed"
                        .to_string(),
                )
                .into());
            }
        }
        None => {
            eprintln!("Person doesn't have an id");
            return Err(ApiErrorType::BadRequest("Person doesn't have an id".to_string()).into());
        }
    }

    persons::update(pool.inner(), &person).await?;

    Ok(APIResponse::from(person))
}

// GET /api/persons/<id>
/// Get a person by id
#[get("/api/persons/<id>")]
pub async fn get_person(_session: Session, pool: &State<PgPool>, id: String) -> APIResult<Person> {
    let id = uuid::Uuid::parse_str(&id)?;
    let person = persons::get(pool.inner(), id).await?;
    Ok(APIResponse::from(person))
}

/// GET /api/persons?q=<query>
/// Search for persons
///
/// Arguments
/// * `query` - Query string as [`String`] - search for persons with first name, last name, orcid, gnd, or ror. Case Insensitive
/// * `limit` - Limit of results as [`Option<u16>`] - optional, default is 10
///
/// Returns
/// * `Json<ApiResult<Vec<Person>>>` - Api Result with Json List of persons matching the query
#[get("/api/persons?<query>&<limit>")]
pub async fn search_persons(
    _session: Session,
    pool: &State<PgPool>,
    query: String,
    limit: Option<usize>,
) -> APIResult<Vec<Person>> {
    let limit = limit.unwrap_or(10) as i64;
    let result = persons::search(pool.inner(), &query, limit).await?;
    Ok(APIResponse::from(result))
}

/// DELETE /api/persons/<id>
/// Delete a person by id
#[delete("/api/persons/<id>")]
pub async fn delete_person(_session: Session, pool: &State<PgPool>, id: String) -> APIResult<()> {
    let id = uuid::Uuid::parse_str(&id)?;
    persons::delete(pool.inner(), id).await?;
    Ok(APIResponse::from(()))
}
